[package]
name = "moan"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
anyhow = "1.0.56"
derive_more = "0.99.17"
regex = "1.5.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
thiserror = "1.0.30"

[dev-dependencies]
tempfile = "3.3.0"
